services:
  db:
    image: postgres:15
    container_name: big_kahuna_db
    environment:
      POSTGRES_USER: hr_platform
      POSTGRES_PASSWORD: vulnerable_password_123
      POSTGRES_DB: big_kahuna_hr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hr_network

  backend:
    build: ./backend
    container_name: big_kahuna_backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-mini}
      - DATABASE_URL=postgresql://hr_platform:vulnerable_password_123@db:5432/big_kahuna_hr
      - SECRET_KEY=super_secret_key_that_should_be_random
      - JWT_SECRET_KEY=another_weak_secret_for_jwt
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - hr_network

  frontend:
    build: ./frontend
    container_name: big_kahuna_frontend
    environment:
      - VUE_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - hr_network

  nginx:
    image: nginx:alpine
    container_name: big_kahuna_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - hr_network

volumes:
  postgres_data:

networks:
  hr_network:
    driver: bridge 