services:
  db:
    image: postgres:15
    container_name: big_kahuna_db
    environment:
      POSTGRES_USER: big_kahuna_hr
      POSTGRES_PASSWORD: vulnerable_password_123
      POSTGRES_DB: big_kahuna_hr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "big_kahuna_hr"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
      start_interval: 5s

  backend:
    build: ./backend
    container_name: big_kahuna_backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4.1-mini}
      - DATABASE_URL=postgresql://big_kahuna_hr:vulnerable_password_123@db:5432/big_kahuna_hr
      - SECRET_KEY=super_secret_key_that_should_be_random
      - JWT_SECRET_KEY=another_weak_secret_for_jwt
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      db:
          condition: service_healthy
    networks:
      - hr_network

  frontend:
    build: ./frontend
    container_name: big_kahuna_frontend
    environment:
      - VUE_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hr_network

  nginx:
    image: nginx:alpine
    container_name: big_kahuna_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - hr_network

  hacker:
    image: php:8.0-apache
    container_name: big_kahuna_hacker
    ports:
      - "8888:80"
    volumes:
      - ./assets/XSS:/var/www/html

volumes:
  postgres_data:

networks:
  hr_network:
    driver: bridge 